# Generated by Django 4.0 on 2022-01-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('date', models.CharField(max_length=120)),
                ('time', models.CharField(max_length=120)),
                ('groundtype', models.CharField(max_length=120)),
                ('selectground', models.CharField(max_length=120)),
            ],
        ),
    ]
