# Generated by Django 4.0 on 2022-01-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='number',
            field=models.CharField(default='phone number', max_length=10),
        ),
    ]
