# Generated by Django 4.0.1 on 2022-02-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookings_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CricketTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newdate', models.DateTimeField()),
                ('c1_t1', models.CharField(max_length=20)),
                ('c1_t2', models.CharField(max_length=20)),
                ('c1_t3', models.CharField(max_length=20)),
                ('c2_t1', models.CharField(max_length=20)),
                ('c2_t2', models.CharField(max_length=20)),
                ('c2_t3', models.CharField(max_length=20)),
                ('c3_t1', models.CharField(max_length=20)),
                ('c3_t2', models.CharField(max_length=20)),
                ('c3_t3', models.CharField(max_length=20)),
                ('c4_t1', models.CharField(max_length=20)),
                ('c4_t2', models.CharField(max_length=20)),
                ('c4_t3', models.CharField(max_length=20)),
            ],
        ),
    ]
