# Generated by Django 4.0.1 on 2022-02-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_crickettiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crickettiming',
            name='newdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='newdate'),
        ),
    ]
